// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIcvwFe3TAXjFtbaiVmOYvVt0qextkndI',
    appId: '1:953159844691:web:96f2988bbd9075db7dd7a6',
    messagingSenderId: '953159844691',
    projectId: 'pfinance-dev',
    authDomain: 'pfinance-dev.firebaseapp.com',
    storageBucket: 'pfinance-dev.appspot.com',
    measurementId: 'G-8BGQE9E94H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAS1mL1CRIVixbqJomnddF6g2LtagGjUc',
    appId: '1:953159844691:android:0aabb8585d165bf67dd7a6',
    messagingSenderId: '953159844691',
    projectId: 'pfinance-dev',
    storageBucket: 'pfinance-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgjpalb9LbNtJSq0R1oXSiTqOgKpfwwDk',
    appId: '1:953159844691:ios:163a4e8108d5b8f77dd7a6',
    messagingSenderId: '953159844691',
    projectId: 'pfinance-dev',
    storageBucket: 'pfinance-dev.appspot.com',
    iosClientId: '953159844691-pcsg4fef5hi6oa0fveqf15di2l47jhtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgjpalb9LbNtJSq0R1oXSiTqOgKpfwwDk',
    appId: '1:953159844691:ios:163a4e8108d5b8f77dd7a6',
    messagingSenderId: '953159844691',
    projectId: 'pfinance-dev',
    storageBucket: 'pfinance-dev.appspot.com',
    iosClientId: '953159844691-pcsg4fef5hi6oa0fveqf15di2l47jhtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfinance',
  );
}
